server:
  port: 0

spring:
  application:
    name: eureka-usergroup
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/
    driver-class-name: org.postgresql.Driver
    username: bookp
    password: bookp

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1 #하트비트 인터벌
    lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막

logging:
  level:
    com.book.eurekausergroup: DEBUG

token:
  expiration_time: 86400000
  secret: user
